## Manupliation des objets ndarry 

In [1]:
# Importer les biblothéques
import numpy as np


## 1. Concatenation 

In [18]:
# la fontion hstack 
A = np.ones((3,3))
B = np.zeros((3 ,3))

if A.shape[0] == B.shape[0] :
    C = np.hstack((A , B))
    
print(A)
print(B)
print(f"hstack((A,B)) = {C}" )



# la fonction vstack 

if A.shape[1] == B.shape[1] :
    D = np.vstack((A,B))

print(f"vstack((A,B)) = {D}")



# la fonction concatenate :


# avce axis  = 0 => la fonction vstack 

E = np.concatenate((A,B) , axis = 0)
print("concatenate avce Axis = 0 :")
print("\t" , end="")
print(E)


# avce axis  = 1 => la fonction hstack 

F = np.concatenate((A,B) , axis = 1)
print("concatenate avce Axis = 1 :")
print("\t" , end="")
print(F)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
hstack((A,B)) = [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
vstack((A,B)) = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
concatenate avce Axis = 0 :
	[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
concatenate avce Axis = 1 :
	[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


## 2. les fonctions des Redimensionnement des ``ndarry``:

In [41]:
# une matrice (3,4) => (4,3)

A = np.array([[1 , 2 , 3, 4] ,
            [5, 6 , 7 , 8],
            [9 , 10 , 11 , 12]])
print(A)
print(A.shape)


# redi vers (4 ,3)

A = A.reshape((4,3))
print("===== Respahe(4,3) =========")
print(A)
print(A.shape)


# 

# Création d'un tableau unidimensionnel
a = np.array([1, 2, 3, 4, 5, 6])

# Remodelage en un tableau 2D de 3 lignes et 2 colonnes
result = np.reshape(a, (3, 2))
result

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
===== Respahe(4,3) =========
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# la fonction sequeeze()

B = np.array([1 , 2 , 4 , 5])
print(B)

print(B.shape)

# redi vers (4,1)
B = B.reshape((B.shape[0] , 1))
print(B.shape)

# la fonction sequeeze()
C = np.squeeze(B)
print(C)
print(C.shape)

B.squeeze()

[1 2 4 5]
(4,)
(4, 1)
[1 2 4 5]
(4,)


array([1, 2, 4, 5])

In [44]:
# la fonction ravel :

A = np.random.randn(3 ,2)
A
print(A.shape)
B = np.ravel(A)
print(B.shape)

(3, 2)
(6,)
