In [15]:
import numpy as np
A = np.array([21,3,4,5 , 0])

A.sort()

print(A)


# dans le cas A.ndim = 2 

A = np.array([
    [3 , 1 , 4] ,
    [10 , 1 , 7] ,

    [ 4 , 0 , 1]
])


A.sort(axis=0)

print(A)

[ 0  3  4  5 21]
[[ 3  0  1]
 [ 4  1  4]
 [10  1  7]]


# axis 

![image](../images/image.png)

i


In [30]:
A = np.ones((1_000,1_000))

f = lambda x : x +1 

print(f(A))



[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]


In [31]:
for i in range(A.shape[0]) :
    for j in range(A.shape[1]) :
        A[i,j] = f(A[i,j])

